# Based on HLEnhanced's .travis.yml, credits to Shepard for writing it!

# Use the C base
language: c

# Linux - use Ubuntu 14.04 Trusty Tahr instead of 12.04 Precise Pengolin, this
# is required for the correct version of libsdl2-dev.
sudo: required
dist: trusty

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libsdl2-dev
    - linux-libc-dev
    - gcc-6-multilib
    - g++-6-multilib

matrix:
  allow_failures:
    # Mac OS X Mavericks 10.9.5 (Xcode 6.1)
    - os: osx
  include:
    #debug
    - os: linux
      env: COMPILER=gcc-6 BUILD_RULES="-DOPT:STRING=debug -DGAME_BASE_DIRECTORY=dummy" OPT=debug

    #optimized
    - os: linux
      env: COMPILER=gcc-6 BUILD_RULES="-DOPT:STRING=opt -DGAME_BASE_DIRECTORY=dummy" OPT=opt
  
    #optimized fast
    - os: linux
      env: COMPILER=gcc-6 BUILD_RULES="-DOPT:STRING=opt-fast -DGAME_BASE_DIRECTORY=dummy" OPT=opt-fast

before_install:
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      sudo dpkg --add-architecture i386
      sudo apt-get -qq update
      sudo apt-get install -y linux-libc-dev:i386
    else
      brew update
    fi

install:
  # Prepare the dependencies
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}
  # Get the latest CMake version
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="http://www.cmake.org/files/v3.6/cmake-3.6.2-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    else
      CMAKE_URL="http://www.cmake.org/files/v3.6/cmake-3.6.2-Darwin-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/CMake.app/Contents/bin:${PATH}
    fi

before_script:
  # Move to build directory
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build && cd build

script:
  # Just execute the cmake and make commands
  - |
    if [[ "${COMPILER}" == "gcc-6" ]]; then
      cmake -DCMAKE_CXX_COMPILER="g++-6" -DCMAKE_C_COMPILER="gcc-6" ${BUILD_RULES} ..
    else
      cmake ${BUILD_RULES} ..
    fi
  - make

after_success:
  - zip Metamod-P-${OPT}-Linux.zip metamod/metamod.so
  - zip Plugins-${OPT}-Linux.zip stub_plugin/stub_plugin.so trace_plugin/trace_plugin.so wdmisc_plugin/wdmisc_plugin.so
  
notifications:
  email: false
  
deploy:
  provider: releases
  api_key:
    secure: jIO7UlV3rA2X+yaNew+LLfguSOPG/5ZHK+W+xxMHJfOzKgEgR5qlPeB0zCLCmrUse1rxWB67DoRTsdpxFBtpIz9uSlsFJnxtmSI4aRs5WXGpmdjittmX7mp/AE8+ejF7I2QZonfNguCEblrrG22OV9az9a86FFUebsDc547aLcmYaIpNXnV0/qksu2HtKfHuMkWY8gvlYoATWYtANhj5AuIX/wBukx6/UTPTjy6W8oqz5Ou3wY3xCXyU3d5RPVguRKJ8G9mzInAUDT4uyEHpvMtX8b0sH2r1Xw+0/xy42VQMICPQZrlaKOFbW5UoVrUDKlry79NFa0B910Wqa6HLeWwOZtcLEkbVY/l3+faT5GN4arTZZMsTT1AkDGYRWqq/5kN7pGi2rDUF1hKLMJOlbhrc00RG06gJKwRjuZr+A2HeitRYIRLf4NyVAZE7cywIf4mQyqOccVQELAjfHRbSAcwCMi0zaYVlHc/To7WC2PVm7iontMGBSySsnJguxbBtzLPFUP+622QMjNbEXuVRqbncpb87xtWYvFgUY7RXw+kh6L193DPVQAMyI+2LOaLd+iFfThcBlYEo0CYwGeqsF5L68Qxj6tTFUpjfzo7eSdE0oUtTndAU4JPvmlzAROalFkZZ+7LwFByYPgOqguuuPtnTq9JgZw9+IBYGLhIskHs=
  file:
    - "Metamod-P-${OPT}-Linux.zip"
    - "Plugins-${OPT}-Linux.zip"
  skip_cleanup: true
  on:
    tags: true
