# Based on HLEnhanced's .travis.yml, credits to Shepard for writing it!

# Use the C base
language: c

# Linux - use Ubuntu 14.04 Trusty Tahr instead of 12.04 Precise Pengolin, this
# is required for the correct version of libsdl2-dev.
sudo: required
dist: trusty

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libsdl2-dev
    - linux-libc-dev
    - gcc-6-multilib
    - g++-6-multilib

matrix:
  allow_failures:
    # Mac OS X Mavericks 10.9.5 (Xcode 6.1)
    - os: osx
  include:
    #debug
    - os: linux
      env: COMPILER=gcc-6 BUILD_RULES="-DOPT:STRING=debug" OPT=debug

    #optimized
    - os: linux
      env: COMPILER=gcc-6 BUILD_RULES="-DOPT:STRING=opt" OPT=opt
  
    #optimized fast
    - os: linux
      env: COMPILER=gcc-6 BUILD_RULES="-DOPT:STRING=opt-fast" OPT=opt-fast

before_install:
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      sudo dpkg --add-architecture i386
      sudo apt-get -qq update
      sudo apt-get install -y linux-libc-dev:i386
    else
      brew update
    fi

install:
  # Prepare the dependencies
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}
  # Get the latest CMake version
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="http://www.cmake.org/files/v3.6/cmake-3.6.2-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    else
      CMAKE_URL="http://www.cmake.org/files/v3.6/cmake-3.6.2-Darwin-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/CMake.app/Contents/bin:${PATH}
    fi

before_script:
  # Move to build directory
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build && cd build

script:
  # Just execute the cmake and make commands
  - |
    if [[ "${COMPILER}" == "gcc-6" ]]; then
      cmake -DCMAKE_CXX_COMPILER="g++-6" -DCMAKE_C_COMPILER="gcc-6" ${BUILD_RULES} ..
    else
      cmake ${BUILD_RULES} ..
    fi
  - make

after_success:
  - zip Metamod-P-${OPT}-Linux.zip metamod/metamod.so
  - zip Plugins-${OPT}-Linux.zip stub_plugin/stub_plugin.so trace_plugin/trace_plugin.so wdmisc_plugin/wdmisc_plugin.so
  
notifications:
  email: false
  
deploy:
  provider: releases
  api_key:
    secure: rKa8aG7Uj0RbN4/WK2ajt0CeAC8tLyvJk+AEbd5gaQaOAHtBH/E8c52l358zLBZs/8fZRrAPWDOmWbLAC+wqoAF6NA4u71JXoRDGZEX0tHoim6WBvx7OLAejherBeqlOzbJNoB9AnmIimA8a5N2w8MaXqIKq8bQ8acAnJBZI3AVIhUtltFfzWrmIfZw39xL66M/uUBBwpm685fKsCYdcou4toWr7n6g3PfVnmqnYpzO/voPkc0RvTgOMmaie1DY64ra1BLZOELN+KiVSvcgFeqlxXgnztNLeW+1Z1JTO+sMl+v4vys1O+Q485X2Bgkia0u0py8989qM06YtafBiMUIuE5Vubq2k1Vwaqbz1TqNqkO4M6TvVJLTYKhRpB0NzAt9j70KeUDDorhSHofMZa6RAqUlzXl6qKlA0f/PB+scp2jkREt7l0cURFJoCVx90/qrgPIBFS8LHRgnRBBDerGrVhXW9AK/vuT/ptbZTQNWYDfZwqG7oqjWhVT5Suf1pnlv1TxPNV47R1SjgOPJL2yKwGA/7BSqrqqMHUa31yitXrsTEFaSXPlNiBJ4qyrsQKHQdqkzeaXs7XHP75JDLYv/QoWI28SXAjoeuYIKLxzlIgXER9pSSNefseSAlBM1XoWPWU33xp0vncK0DMPBs9vjjS4atKJN+uWq+XAYoMfk8=
  file:
    - "Metamod-P-${OPT}-Linux.zip"
    - "Plugins-${OPT}-Linux.zip"
  skip_cleanup: true
  on:
    tags: true
